# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'GrandRedBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GrandRedBook
  pod 'Alamofire'

  target 'GrandRedBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GrandRedBookUITests' do
    # Pods for testing
  end

end
